### ISSUE TITLE
Add fingerprints (Contact)

### ISSUE THREAD

**Issue by PotatoMexicano** [Mariano-Github/Edge-Drivers-Beta#125]
Hi,

Would it be possible to add a new contact device?

```yml
 - id: "_TZ3000_qld3y9tu/Close Sensor"
   deviceLabel: TS0203 Close Sensor
   manufacturer: _TZ3000_qld3y9tu
   model: TS0203
   deviceProfileName: contact-battery-profile
```

I imported the (your) driver into my HUB but my device is not recognized, just a Device Information card with unrepresented HTML code.
