### ISSUE TITLE
Add Fingerprints

### ISSUE THREAD

**Issue by wllnrds** [Mariano-Github/Edge-Drivers-Beta#134]
Hello, can you add this fingerprints?

# Humid Temp Sensor

``` yaml
  - id: "NovaDigital/STU-ZBD"
    deviceLabel: Nova Digitagl Temp Humid Sensor Zigbee with Display
    manufacturer: _TZE284_hdyjyqjm
    model: TS0601
    deviceProfileName: temp-humid-battery
```

# Multi Switch

``` yaml
   - id: "NovaDigital/ZTS-2"
    deviceLabel: Nova Digital Two Switch
    manufacturer: _TZ3000_jjdkhueq
    model: TS0002
    deviceProfileName: two-switch
```
