### ISSUE TITLE
Add Fingerprint (Motion Sensor)

### ISSUE THREAD

**Issue by damu-u** [Mariano-Github/Edge-Drivers-Beta#135]
Hi, Can you add TS0202 Motion Sensor? (_TZ3000_c8ozah8n)

Motion Sensor
```yml
  - id: "_TZ3000_c8ozah8n/Motion"
    deviceLabel: TS0202 Motion Sensor
    manufacturer: _TZ3000_c8ozah8n
    model: TS0202
    deviceProfileName: motion-battery
```
