### ISSUE TITLE
Add TERNCY-SM01-D3 multi switch

### ISSUE THREAD

**Issue by ibr23** [Mariano-Github/Edge-Drivers-Beta#58]
Hi Mariano,

can you please add this fingerprint to your multi-switch driver. It doesn't appear to report a manufacturer id.

```
zigbeeManufacturer:
  - id: "TERNCY-SM01-D3"
    deviceLabel: TERNCY-SM01-D3
    model: TERNCY-SM01-D3
    deviceProfileName: three-switch
```

Thanks
Ian
