### ISSUE TITLE
Add tuya plug

### ISSUE THREAD

**Issue by lansi951** [Mariano-Github/Edge-Drivers-Beta#59]
```yaml
- id: "TS011F/_TZ3000_gvn91tmx"
  deviceLabel: Aubess Plug
  manufacturer: _TZ3000_gvn91tmx
  model: TS011F
  deviceProfileName: single-switch-plug
```
https://aliexpress.com/item/1005005122047276.html
https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html
